### ISSUE TITLE
OPAM erroneously reports that my environment is out of sync.

### ISSUE THREAD

**Issue by vzaliva** [ocaml/opam#2159]
My .bash_profile has following lines at the end:

    # OPAM configuration
    if [ -f ~/.opam/opam-init/init.sh ]; then
      . ~/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true
    fi
    export PATH
    export MANPATH

however when I do 'opam switch'  (wihout any other arguments) it says:

    [WARNING] The environment is not in sync with the current switch.
              You should run: eval `opam config env`

After 'eval `opam config env`' the warning goes away. 
I did the following to see what changes are required:

    $ opam switch
    $ env > pre
    $ eval `opam config env`
    $ env > post
    $ diff -U 0 pre post

The result is:

    -MANPATH=/opt/local/man:/opt/local/share/man:/usr/share/man:/usr/local/man:/Users/lord/man::/Users/lord/.opam/system/man
    +MANPATH=/Users/lord/.opam/system/man:/opt/local/man:/opt/local/share/man:/usr/share/man:/usr/local/man:/Users/lord/man

Apparently the issue is where OPAM adds it's path to MANPATH: at the beginning or towards the end.

I am using OPAM 1.2.1 installed via 'macports' under MacOS.

**Comment by AltGr** [comment]
This is fixed in 1.2.2, please upgrade!
Thanks for reporting.

**Comment by gkoller** [comment]
I'm afraid the issue remains using version 1.2.2 installed by means of MacPorts.

After initializing Opam using `opam init` and starting a new (login) shell. Opam complains about my environment not being in sync. Testing the differences between my pre and post ``eval `opam config env``` demonstrates the same difference in the MANPATH configuration as reported by @vzaliva:

```bash
$ opam switch
$ env > pre
$ eval `opam config env`
$ env > post
$ diff -U 0 pre post
```
Namely:
```bash
-MANPATH=:/opt/local/share/man:/Users/gkoller/man:/Users/gkoller/.opam/system/man
+MANPATH=:/Users/gkoller/.opam/system/man:/opt/local/share/man:/Users/gkoller/man
```
It seems the issue is with the code the verifies whether the environment is in sync as the environment is 'working'. Eg. `opam switch` complains, but:

```bash
$ which ocaml
/Users/gkoller/.opam/4.02.3/bin/ocaml
```
Clearly show the proper compiler being selected by virtue of the Opam environment.

**Comment by rleonid** [comment]
I am also experiencing this problem, where I have to ``eval `opam config env` `` twice in order to get the switch to sync. Following @gkoller, my difference also stems from MANPATH, where the first time it is set to:

```
MANPATH=/Users/leonidrozenberg/.opam/4.03.0/man:
```
and the second time to:
```
MANPATH=:/Users/leonidrozenberg/.opam/4.03.0/man
``` 

I guess, the placement of the colon matters?

**Comment by breadmj** [comment]
I'm also experiencing same issue, on version 1.2.2.
Same problem, the colon in MANPATH.

opam v1.2.2
macOS sierra
installed by homebrew

**Comment by johnduck** [comment]
I have exactly same issue on version 1.2.2 on my Ubuntu Gnome 16.04 desktop.
In `.bashrc`, the command `eval $(opam config env)` is written, but it does not work.
I fixed this problem by writing `eval $(opam config env)` twice in `.bashrc`.

**Comment by LukeXuan** [comment]
Same here as @johnduck . Need to run twice to kill the warning.

**Comment by vzaliva** [comment]
I am also still having this problem. This bug needs to be reopened as it was not fixed.

**Comment by wintersteiger** [comment]
I just hit a problem with exactly the same symptoms (eval ... twice makes it work), because of a botched, mixed Windows+Linux opam setup. `~/.opam/init.sh` refers to `variables.sh` and others by absolute paths, i.e., if the `.opam` directory gets moved or when cygwin rewrites the paths to `/cygdrive/...` in place of `/mnt/...` then the init script ultimately has no effect on the environment, but `opam config env` can fix that by running twice. The proper fix is of course to make sure the right paths are used in the initialization scripts.

**Comment by freelyyu** [comment]
![ydq b91c t75 jz 6nz_a](https://user-images.githubusercontent.com/39991677/47898544-4b609a80-deb1-11e8-9cc3-8f4e6bf40026.png)
as shown in the picture,I meet with the problem
