### ISSUE TITLE
`opam init` breaks fish shell with configuration

### ISSUE THREAD

**Issue by dongcarl** [ocaml/opam#2255]
Tested on Ubuntu, Mac OS X, and FreeBSD.

When I invoke opam init, this is inserted in my config.fish

```
. /home/dongcarl/.opam/opam-init/init.fish > /dev/null 2> /dev/null or true
```

I'm not sure exactly how but this line renders the fish shell completely unusable. I have resorted to replacing the aforementioned line with `eval (opam config env)`

**Comment by AltGr** [comment]
Can you give the precise opam version ? (`opam config report`)

The output of manually running `. /home/dongcarl/.opam/opam-init/init.fish` could help.

Thanks for reporting!

**Comment by dongcarl** [comment]
Here's the config report
```
# OPAM config report
# opam-version    1.2.2 
# self-upgrade    no
# os              darwin
# external-solver aspcud $in $out $criteria
# criteria        -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
# jobs            4
# repositories    1* (http), 1 (version-controlled)
# pinned          0
# current-switch  system*
# last-update     2015-07-11 14:29
```

I've talked to people on the mailing list about this and come up with a fix thanks to Zanchey on fish shell IRC. 

The proper configuration would have the following files:

config.fish
```
# OPAM configuration
. /Users/dongcarl/.opam/opam-init/init.fish > /dev/null 2> /dev/null; or true
```

init.fish
```
# Load the environment variables
. /Users/dongcarl/.opam/opam-init/variables.fish > /dev/null 2> /dev/null; or true
```

The above two files have a semicolon before the "or true"

variables.fish
```
set -gx PATH "/Users/dongcarl/.opam/system/bin" $PATH;
set -gx OCAML_TOPLEVEL_PATH "/Users/dongcarl/.opam/system/lib/toplevel";
set -gx PERL5LIB "/Users/dongcarl/.opam/system/lib/perl5:$PERL5LIB";
set -gx MANPATH $MANPATH "/Users/dongcarl/.opam/system/man";
set -gx OPAMUTF8MSGS "1";
set -gx CAML_LD_LIBRARY_PATH "/Users/dongcarl/.opam/system/lib/stublibs:/usr/local/lib/ocaml/stublibs";
```

The above file doesn't have double quotes around the $PATH and the $MANPATH

I've been looking at the repository and couldn't figure out which files to change... opamState looks like the place to fix things in variables.fish but it says `(* PATH is always set *)`. Help would be greatly appreciated!

**Comment by rgoulter** [comment]
The `variables.fish` file contains a line:
```
set -gx PATH "/home/richard/.opam/4.02.1/bin" "$PATH";
```
While `"$PATH"` may be good bash, in fish it breaks the `PATH`.

**Comment by berdario** [comment]
I have the same problem

This seems to be issue #2244 , which has already been fixed

When can we expect 1.2.3 to be released with this fix?

**Comment by raichoo** [comment]
Same issue here.

**Comment by dongcarl** [comment]
I just installed Arch Linux and wanted to try opam, and this still happens.

**Comment by macleginn** [comment]
I just installed opam under OS X, and fish got broken as reported above. Manually adding two semicolons in config.fish and init.fish and removing redundant quotes from variables.fish brought it back to life.

**Comment by talex5** [comment]
Just hit the same problem (on OS X). For anyone else searching on the error message, this is the output you see after starting a new shell:

    Last login: Wed Jan  6 14:41:05 on ttys006
    fish: Unknown command 'uname'
    /usr/local/Cellar/fish/2.2.0/share/fish/functions/__fish_pwd.fish (line 1): uname
										^
    in command substitution
	    called on line -1 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/__fish_pwd.fish

    from sourcing file /usr/local/Cellar/fish/2.2.0/share/fish/functions/__fish_pwd.fish
	    called on standard input

    in command substitution
	    called on standard input

    in command substitution
	    called on standard input

    switch: Expected exactly one argument, got 0

    /usr/local/Cellar/fish/2.2.0/share/fish/functions/__fish_pwd.fish (line 1): switch (uname)
										       ^
    from sourcing file /usr/local/Cellar/fish/2.2.0/share/fish/functions/__fish_pwd.fish
	    called on standard input

    in command substitution
	    called on standard input

    in command substitution
	    called on standard input

    fish: Unknown command '__fish_pwd'
    fish: echo $_ " "; __fish_pwd
		       ^
    in command substitution
	    called on standard input

    Welcome to fish, the friendly interactive shell
    Type help for instructions on how to use fish
    /usr/local/Cellar/fish/2.2.0/share/fish/functions/type.fish (line 1): seq (count $argv)
									  ^
    in command substitution
	    called on line 2 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/type.fish

    in function 'type'
	    called on standard input
	    with parameter list '-q -p command-not-found'

    in function '__fish_command_not_found_setup'
	    called on line 6 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/fish_prompt.fish
	    with parameter list 'hostname'

    in event handler: handler for generic event 'fish_command_not_found'

    /usr/local/Cellar/fish/2.2.0/share/fish/functions/type.fish (line 1): seq (count $argv)
									  ^
    in command substitution
	    called on line 2 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/type.fish

    in function 'type'
	    called on standard input
	    with parameter list '-p -q pkgfile'

    in function '__fish_command_not_found_setup'
	    called on line 6 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/fish_prompt.fish
	    with parameter list 'hostname'

    in event handler: handler for generic event 'fish_command_not_found'

    fish: Unknown command 'hostname'
    /usr/local/Cellar/fish/2.2.0/share/fish/functions/fish_prompt.fish (line 1): hostname|cut -d . -f 1
										 ^
    in command substitution
	    called on line 4 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/fish_prompt.fish

    in function 'fish_prompt'
	    called on standard input

    in command substitution
	    called on standard input

    fish: Unknown command 'uname'
    /usr/local/Cellar/fish/2.2.0/share/fish/functions/prompt_pwd.fish (line 1): uname
										^
    in command substitution
	    called on line -1 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/prompt_pwd.fish

    from sourcing file /usr/local/Cellar/fish/2.2.0/share/fish/functions/prompt_pwd.fish
	    called on line 6 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/fish_prompt.fish

    in command substitution
	    called on line 4 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/fish_prompt.fish

    in command substitution
	    called on line 4 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/fish_prompt.fish

    in function 'fish_prompt'
	    called on standard input

    in command substitution
	    called on standard input

    switch: Expected exactly one argument, got 0

    /usr/local/Cellar/fish/2.2.0/share/fish/functions/prompt_pwd.fish (line 3): switch (uname)
										       ^
    from sourcing file /usr/local/Cellar/fish/2.2.0/share/fish/functions/prompt_pwd.fish
	    called on line 6 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/fish_prompt.fish

    in command substitution
	    called on line 4 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/fish_prompt.fish

    in command substitution
	    called on line 4 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/fish_prompt.fish

    in function 'fish_prompt'
	    called on standard input

    in command substitution
	    called on standard input

    fish: Unknown command 'sed'
    /usr/local/Cellar/fish/2.2.0/share/fish/functions/prompt_pwd.fish (line 2): 	echo $PWD | sed -e "s|^$realhome|~|" $args_pre -e 's-\([^/.]\)[^/]*/-\1/-g' $args_post
												^
    in function 'prompt_pwd'
	    called on line 6 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/fish_prompt.fish

    in command substitution
	    called on line 4 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/fish_prompt.fish

    in function 'fish_prompt'
	    called on standard input

    in command substitution
	    called on standard input

    fish: Unknown command '__fish_pwd'
    fish: echo $_ " "; __fish_pwd
		       ^
    in command substitution
	    called on standard input

    tal@ >

**Comment by robo-hamburger** [comment]
I fixed this on my osx install by changing the line where the path is set to be:

`set PATH "/Users/amcharg/.opam/system/bin" $PATH;`

Based on the advice in this comment: https://github.com/fish-shell/fish-shell/issues/527#issuecomment-12436286 for setting paths in fish. My guess is the way it is being set here by opam is incorrect? Not much of a fish expert yet but it the spew of errors seems to indicate its clobbering path.

**Comment by roryokane** [comment]
Between my pull request #2424 and the earlier pull request #2169, we now have all the fixes to solve this issue. We just need to wait for a release of OPAM that contains those fixes.

Until then, here are instructions for manually fixing your files generated in `~/.opam/opam-init/`:

#### `init.fish`

Replace `.` with `source` and add a semicolon before ` or`:

```diff
-. /Users/you/.opam/opam-init/variables.fish > /dev/null 2> /dev/null or true
+source /Users/you/.opam/opam-init/variables.fish > /dev/null 2> /dev/null; or true
```

#### `variables.fish`

Unquote `$PATH` and `$MANPATH`:

```diff
-set -gx PATH "/Users/you/.opam/system/bin" "$PATH";
+set -gx PATH "/Users/you/.opam/system/bin" $PATH;
 set -gx OCAML_TOPLEVEL_PATH "/Users/you/.opam/system/lib/toplevel";
 set -gx PERL5LIB "/Users/you/.opam/system/lib/perl5:$PERL5LIB";
-set -gx MANPATH "$MANPATH" "/Users/you/.opam/system/man";
+set -gx MANPATH $MANPATH "/Users/you/.opam/system/man";
 set -gx OPAMUTF8MSGS "1";
 set -gx CAML_LD_LIBRARY_PATH "/Users/you/.opam/system/lib/stublibs:/usr/local/lib/ocaml/stublibs";
```

Optionally, if you want the file to look neater, you can also remove the ending semicolons `;`. They are unnecessary but shouldn’t harm anything.

**Comment by KyleLH** [comment]
Thought I should let people know, I'm still getting this error. The fix posted here is awesome, thanks @roryokane. However, it's probably annoying if one manages to miss this. I installed opam via homebrew, was this change not changed there as well?

**Comment by tathanhdinh** [comment]
Thanks @roryokane , your fix works for me also.

**Comment by martinklepsch** [comment]
Also installed `opam` via homebrew and was initially amazed by the fact that there was special guidance for fish users. Then ran into this as well :) Would be great to have this fixed by default. 👍

**Comment by talex5** [comment]
Note: this doesn't just affect `init`. My shell config is broken every time I do `opam switch` too.

**Comment by johshoff** [comment]
As suggested in #2169, I'd like to encourage making a point release with these two fixes. Current behavior breaks the configuration of fish shells when installing the latest release, 1.2.2 (released a year ago, so I'm assuming this is what most package managers have).

**Comment by tchajed** [comment]
@AltGr: could you please release a new 1.2.3 version of opam with these fixes? df51212ef adds 75 more commits over 1.2.2 and fixes the most pressing concern (`opam init` breaking the shell) for Fish users.

**Comment by ariasuni** [comment]
I lost half an hour to find this bug report, so it would be nice to have this to work.

**Comment by mfaerevaag** [comment]
Almost a year later and this is problem in 1.2.2.

**Comment by sharno** [comment]
When is opam 1.2.3 going to be released? I'm on MacOS and still this error is present almost 2 years after the issue appeared.

**Comment by cartazio** [comment]
I'm still hitting this issue :(

**Comment by kyleholzinger** [comment]
Who in the world is responsible for deploying this project to homebrew? I wanna know who to ping lol

**Comment by sharno** [comment]
If you're still hitting this issue, I'd suggest to try opam 2.0 beta, it'll definitely fix the issue and seems stable to me

**Comment by dogweather** [comment]
Still an issue on OSX with Homebrew. Not a problem, though, on Fedora.

**Comment by kyleholzinger** [comment]
I'm curious why this was closed if it wasn't fully published 🤔 ++ on publishing this to homebrew, it's the primary package manager for macs

**Comment by rjbou** [comment]
It was closed because the issue has been fixed on master at the time (PR #2424). 
opam 2.0.0  will be released in few days (cf. [rc4](https://opam.ocaml.org/blog/opam-2-0-0-rc4/) and [roadmap](https://opam.ocaml.org/blog/opam-2-0-0-repo-upgrade-roadmap/) posts), but as we don't maintain OS packages ourselves, we contacted OS maintainers to let them know about the roadmap. 
Until it is released, you can upgrade your installed opam as explained in the rc4 blog post.

**Comment by avsm** [comment]
For now, a workaround is to use our brew tap with opam2: `brew install ocaml/ocaml/opam@2`

**Comment by tchajed** [comment]
For the record, with the release of opam 2.0.0 this issue has finally been fixed - thanks @rjbou!

**Comment by johshoff** [comment]
And to add to that, 2.0.0 is now available with `brew install opam` or `brew upgrade opam`. No need for the special brew tap anymore.

**Comment by dan-f** [comment]
I still have this problem on the latest fish/opam:

```
~ $ fish --version
fish, version 2.7.1
~ $ opam --version
2.0.0
```

**Comment by rjbou** [comment]
Scripts in the opam root are installed only in the init step. To update them, run an `opam init --reinit -ni`. It is specified in [blog posts](https://opam.ocaml.org/blog/opam-2-0-0/), but worth adding in the main doc.

**Comment by evanhackett** [comment]
I recently installed opam while using fish, and it did still have 1 problem: it broke my man command by setting $MANPATH, so now my man command can't find anything except ocaml related things.

**Comment by rjbou** [comment]
In #3886, we added the semi colon that permit appending `MANPATH` (cf. #3878). Can you confirm that it resolves your problem ?
We can integrate this fix in the next 2.0.6 release.
