### ISSUE TITLE
"Sorry, no solution found: (...)", but no further information from OPAM

### ISSUE THREAD

**Issue by mato** [ocaml/opam#2717]
Environment:

OPAM 1.2.2 (Debian 1.2.2-5+b2), Debian stretch, aspcud 1.9.1 (Debian 1:1.9.1-2)

Steps to reproduce:
1. `opam switch --alias-of 4.04.0+trunk test`
2. `eval $(opam config env)`
3. `opam install ppx_sexp_conv`

Output from OPAM:

```
Sorry, no solution found: there seems to be a problem with your request.

No solution found, exiting
```

Expected output:

OPAM should tell me what the failing constraint is.

**Comment by AltGr** [comment]
Could you include the output of `opam config report` and the `--debug` output ? Thanks!

**Comment by mato** [comment]
Here you go:

[config.txt](https://github.com/ocaml/opam/files/529149/config.txt)
[debug.txt](https://github.com/ocaml/opam/files/529150/debug.txt)

**Comment by AltGr** [comment]
Should have been fixed. Thanks!

**Comment by yallop** [comment]
@AltGr, could you give any more details about the problem and the fix?

**Comment by mato** [comment]
@AltGr This is still not fixed. 

Recently I have started to hit this exact problem again, with some regularity. I'm unable to figure out what exact combination of packages triggers it (since OPAM does not give any information), but it is seriously blocking my workflow. Would you like me to file a new issue or re-open this one?

**Comment by dbuenzli** [comment]
@mato in any case #3083 is open and apparently the same problem.
