### ISSUE TITLE
Uninformative error message (Eliom for OCaml >= 4.05.0)

### ISSUE THREAD

**Issue by yannham** [ocaml/opam#3083]
When I tried to install eliom on a 4.05.0 switch, I got the following cryptic error message : 

```
% opam install eliom
Sorry, no solution found: there seems to be a problem with your request.

No solution found, exiting
zsh: exit 3     opam install eliom
```

It seems that eliom is not compatible with 4.05.0 since it works on a 4.04.2 switch, but the fact that the error message contains absolutely no information was not very helpful to find the problem.

**Comment by dbuenzli** [comment]
It looks like you are using the internal solver (see the output of `opam config report`) which is broken (see https://github.com/ocaml/opam/issues/2989). Either use the latest opam v2 beta or install a solver (e.g. `apscud`) in your path.

**Comment by yannham** [comment]
It seems that I use `ascpcud`as a solver, isn't it ? Anyway it seems to be installed and accessible from the path.

```
# OPAM config report
# opam-version    1.2.2 
# self-upgrade    no
# os              linux
# external-solver aspcud $in $out $criteria
# criteria        -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
# jobs            4
# repositories    1* (http)
# pinned          0
# current-switch  4.04.2
# last-update     2017-10-27 14:21
```

**Comment by dbuenzli** [comment]
Mmmh indeed there is this https://github.com/ocaml/opam/issues/2717 but it doesn't help. Could you try to run `aspcud --version`.

**Comment by dbuenzli** [comment]
Please run `opam` with `--debug` to maybe spot was is going on (as suggested there).

**Comment by yannham** [comment]
`aspcud` version is 1.9.4, and below are the log with `--debug`
```
00:00.127  STATE                           SWITCH    : 4.05.0
00:00.127  STATE                           COMPILER  : 4.05.0
00:00.127  STATE                           COMPILERS : { 3.07, 3.07+1, 3.07+2, 3.08.0, 3.08.1, 3.08.2, 3.08.3, 3.08.4, 3.09.0, 3.09.1, 3.09.1+metaocaml, 3.09.2, 3.09.3, 3.10.0, 3.10.1, 3.10.2, 3.11.0, 3.11.1, 3.11.2, 3.12.0, 3.12.1, 4.00.0, 4.00.0+debug-runtime, 4.00.0+fp, 4.00.1, 4.00.1+BER, 4.00.1+PIC, 4.00.1+annot, 4.00.1+debug-runtime, 4.00.1+french, 4.00.1+mirage-unix, 4.00.1+mirage-xen, 4.00.1+open-types, 4.00.1+raspberrypi, 4.00.1+short-types, 4.01.0, 4.01.0+32bit, 4.01.0+BER, 4.01.0+PIC, 4.01.0+armv6-freebsd, 4.01.0+fp, 4.01.0+lsb, 4.01.0+musl, 4.01.0+musl+static, 4.01.0+open-types, 4.01.0+profile, 4.02.0, 4.02.0+PIC, 4.02.0+improved-errors, 4.02.0+modular-implicits, 4.02.0+rc1, 4.02.0+trunk, 4.02.1, 4.02.1+32bit, 4.02.1+BER, 4.02.1+PIC, 4.02.1+fp, 4.02.1+modular-implicits-ber, 4.02.1+musl, 4.02.1+musl+static, 4.02.2, 4.02.2+improved-errors, 4.02.2+rc1, 4.02.3, 4.02.3+32bit, 4.02.3+PIC, 4.02.3+buckle-1, 4.02.3+buckle-master, 4.02.3+bytecode-only, 4.02.3+curried-constr, 4.02.3+fp, 4.02.3+musl, 4.02.3+musl+static, 4.02.3+termux, 4.03.0, 4.03.0+32bit, 4.03.0+beta1, 4.03.0+beta1+flambda, 4.03.0+beta1-no-debug, 4.03.0+beta2, 4.03.0+beta2+flambda, 4.03.0+beta2-no-debug, 4.03.0+fPIC, 4.03.0+flambda, 4.03.0+fp, 4.03.0+fp+flambda, 4.03.0+statistical-memprof, 4.03.0+termux, 4.03.0+trunk, 4.03.0+trunk+flambda, 4.03.0+trunk+fp, 4.03.0+trunk+fp+flambda, 4.04.0, 4.04.0+32bit, 4.04.0+BER, 4.04.0+afl, 4.04.0+beta1, 4.04.0+beta1+flambda, 4.04.0+beta2, 4.04.0+beta2+flambda, 4.04.0+bytecode-only, 4.04.0+copatterns, 4.04.0+fPIC, 4.04.0+flambda, 4.04.0+fp, 4.04.0+fp+flambda, 4.04.0+safe-string, 4.04.0+spacetime, 4.04.0+termux, 4.04.0+trunk+forced_lto, 4.04.1, 4.04.1+32bit, 4.04.1+bytecode-only, 4.04.1+fPIC, 4.04.1+flambda, 4.04.1+fp, 4.04.1+fp+flambda, 4.04.1+safe-string, 4.04.1+spacetime, 4.04.2, 4.04.2+32bit, 4.04.2+bytecode-only, 4.04.2+fPIC, 4.04.2+flambda, 4.04.2+fp, 4.04.2+fp+flambda, 4.04.2+safe-string, 4.04.2+spacetime, 4.05.0, 4.05.0+afl, 4.05.0+beta1, 4.05.0+beta1+flambda, 4.05.0+beta2, 4.05.0+beta2+flambda, 4.05.0+beta3, 4.05.0+flambda, 4.05.0+lto, 4.05.0+musl+static+flambda, 4.05.0+rc1, 4.05.0+rc1+flambda, 4.05.0+safe-string, 4.05.0+spacetime, 4.05.0+trunk, 4.05.0+trunk+afl, 4.05.0+trunk+flambda, 4.05.0+trunk+fp, 4.05.0+trunk+fp+flambda, 4.05.0+trunk+safe-string, 4.06.0+beta1, 4.06.0+beta1+afl, 4.06.0+beta1+default-unsafe-string, 4.06.0+beta1+flambda, 4.06.0+beta1+force-safe-string, 4.06.0+beta1+fp, 4.06.0+beta1+fp+flambda, 4.06.0+beta2, 4.06.0+beta2+afl, 4.06.0+beta2+default-unsafe-string, 4.06.0+beta2+flambda, 4.06.0+beta2+force-safe-string, 4.06.0+beta2+fp, 4.06.0+beta2+fp+flambda, 4.06.0+trunk, 4.06.0+trunk+afl, 4.06.0+trunk+flambda, 4.06.0+trunk+fp, 4.06.0+trunk+fp+flambda, 4.06.0+trunk+safe-string, 4.07.0+trunk, 4.07.0+trunk+afl, 4.07.0+trunk+flambda, 4.07.0+trunk+fp, 4.07.0+trunk+fp+flambda, 4.07.0+trunk+unsafe-string, system }
00:00.127  STATE                           REPOS     : { default }
00:00.127  STATE                           PACKAGES  : 7657 packages
00:00.127  STATE                           INSTALLED : { alcotest.0.8.1, astring.0.8.3, base.v0.9.3, base-bigarray.base, base-bytes.base, base-num.base, base-threads.base, base-unix.base, base64.2.2.0, biniou.1.2.0, camlp4.4.05+1, camomile.0.8.6, cmdliner.1.0.2, cohttp.0.99.0, cohttp-lwt.0.99.0, conduit.1.0.0, conf-gmp.1, conf-gmp-powm-sec.1, conf-libpcre.1, conf-m4.1, conf-openssl.1, conf-perl.1, conf-pkg-config.1.0, conf-which.1, conf-zlib.1, configurator.v0.9.1, cppo.1.6.0, cppo_ocamlbuild.1.6.0, cryptokit.1.12, dbm.1.0, depext.1.0.5, easy-format.1.3.0, fieldslib.v0.9.0, fmt.0.8.4, ipaddr.2.8.0, jbuilder.1.0+beta14, jsonm.1.0.1, lambda-term.1.11, lambdasoup.0.6.1, logs.0.6.2, lwt.2.7.1, lwt_react.1.0.0, lwt_ssl.1.0.0, magic-mime.1.1.0, markup.0.7.5, merlin.3.0.3, num.0, oasis.0.4.10, ocaml-compiler-libs.v0.9.0, ocaml-migrate-parsetree.1.0.6, ocamlbuild.0.11.0, ocamlfind.1.7.3, ocamlgraph.1.8.8, ocamlify.0.0.1, ocamlmod.0.0.9, ocamlnet.4.1.4, ocsigenserver.2.8, octavius.1.1.0, pcre.7.3.3, ppx_ast.v0.9.1, ppx_base.v0.9.0, ppx_compare.v0.9.0, ppx_core.v0.9.0, ppx_driver.v0.9.1, ppx_enumerate.v0.9.0, ppx_fields_conv.v0.9.0, ppx_hash.v0.9.0, ppx_js_style.v0.9.0, ppx_metaquot.v0.9.0, ppx_optcomp.v0.9.0, ppx_sexp_conv.v0.9.0, ppx_tools.5.0+4.05.0, ppx_tools_versioned.5.0.1, ppx_traverse_builtins.v0.9.0, ppx_type_conv.v0.9.0, re.1.7.1, react.1.2.1, result.1.2, sexplib.v0.9.2, ssl.0.5.5, stdio.v0.9.0, stringext.1.5.0, topkg.0.9.1, tyxml.4.1.0, uchar.0.0.2, uri.1.9.4, utop.2.0.1, uutf.1.0.1, yojson.1.4.0, zarith.1.7, zed.1.5 }
00:00.127  STATE                           ROOTS     : { alcotest.0.8.1, base-bigarray.base, base-threads.base, base-unix.base, cohttp.0.99.0, cohttp-lwt.0.99.0, depext.1.0.5, lambdasoup.0.6.1, lwt.2.7.1, lwt_ssl.1.0.0, merlin.3.0.3, oasis.0.4.10, ocamlgraph.1.8.8, ocsigenserver.2.8, re.1.7.1, ssl.0.5.5, uri.1.9.4, utop.2.0.1 }
00:00.127  STATE                           REINSTALL : {}
00:00.127  STATE                           State switch-lock loaded in 0.114s
00:00.128  SYSTEM                          locking /home/yago/.opam/4.05.0/lock
00:00.128  STATE                           LOAD-STATE(install)
00:00.148  STATE                           Loaded /home/yago/.opam/state.cache in 0.020s
00:00.243  STATE                           ROOT      : /home/yago/.opam
00:00.243  STATE                           SWITCH    : 4.05.0
00:00.243  STATE                           COMPILER  : 4.05.0
00:00.243  STATE                           COMPILERS : { 3.07, 3.07+1, 3.07+2, 3.08.0, 3.08.1, 3.08.2, 3.08.3, 3.08.4, 3.09.0, 3.09.1, 3.09.1+metaocaml, 3.09.2, 3.09.3, 3.10.0, 3.10.1, 3.10.2, 3.11.0, 3.11.1, 3.11.2, 3.12.0, 3.12.1, 4.00.0, 4.00.0+debug-runtime, 4.00.0+fp, 4.00.1, 4.00.1+BER, 4.00.1+PIC, 4.00.1+annot, 4.00.1+debug-runtime, 4.00.1+french, 4.00.1+mirage-unix, 4.00.1+mirage-xen, 4.00.1+open-types, 4.00.1+raspberrypi, 4.00.1+short-types, 4.01.0, 4.01.0+32bit, 4.01.0+BER, 4.01.0+PIC, 4.01.0+armv6-freebsd, 4.01.0+fp, 4.01.0+lsb, 4.01.0+musl, 4.01.0+musl+static, 4.01.0+open-types, 4.01.0+profile, 4.02.0, 4.02.0+PIC, 4.02.0+improved-errors, 4.02.0+modular-implicits, 4.02.0+rc1, 4.02.0+trunk, 4.02.1, 4.02.1+32bit, 4.02.1+BER, 4.02.1+PIC, 4.02.1+fp, 4.02.1+modular-implicits-ber, 4.02.1+musl, 4.02.1+musl+static, 4.02.2, 4.02.2+improved-errors, 4.02.2+rc1, 4.02.3, 4.02.3+32bit, 4.02.3+PIC, 4.02.3+buckle-1, 4.02.3+buckle-master, 4.02.3+bytecode-only, 4.02.3+curried-constr, 4.02.3+fp, 4.02.3+musl, 4.02.3+musl+static, 4.02.3+termux, 4.03.0, 4.03.0+32bit, 4.03.0+beta1, 4.03.0+beta1+flambda, 4.03.0+beta1-no-debug, 4.03.0+beta2, 4.03.0+beta2+flambda, 4.03.0+beta2-no-debug, 4.03.0+fPIC, 4.03.0+flambda, 4.03.0+fp, 4.03.0+fp+flambda, 4.03.0+statistical-memprof, 4.03.0+termux, 4.03.0+trunk, 4.03.0+trunk+flambda, 4.03.0+trunk+fp, 4.03.0+trunk+fp+flambda, 4.04.0, 4.04.0+32bit, 4.04.0+BER, 4.04.0+afl, 4.04.0+beta1, 4.04.0+beta1+flambda, 4.04.0+beta2, 4.04.0+beta2+flambda, 4.04.0+bytecode-only, 4.04.0+copatterns, 4.04.0+fPIC, 4.04.0+flambda, 4.04.0+fp, 4.04.0+fp+flambda, 4.04.0+safe-string, 4.04.0+spacetime, 4.04.0+termux, 4.04.0+trunk+forced_lto, 4.04.1, 4.04.1+32bit, 4.04.1+bytecode-only, 4.04.1+fPIC, 4.04.1+flambda, 4.04.1+fp, 4.04.1+fp+flambda, 4.04.1+safe-string, 4.04.1+spacetime, 4.04.2, 4.04.2+32bit, 4.04.2+bytecode-only, 4.04.2+fPIC, 4.04.2+flambda, 4.04.2+fp, 4.04.2+fp+flambda, 4.04.2+safe-string, 4.04.2+spacetime, 4.05.0, 4.05.0+afl, 4.05.0+beta1, 4.05.0+beta1+flambda, 4.05.0+beta2, 4.05.0+beta2+flambda, 4.05.0+beta3, 4.05.0+flambda, 4.05.0+lto, 4.05.0+musl+static+flambda, 4.05.0+rc1, 4.05.0+rc1+flambda, 4.05.0+safe-string, 4.05.0+spacetime, 4.05.0+trunk, 4.05.0+trunk+afl, 4.05.0+trunk+flambda, 4.05.0+trunk+fp, 4.05.0+trunk+fp+flambda, 4.05.0+trunk+safe-string, 4.06.0+beta1, 4.06.0+beta1+afl, 4.06.0+beta1+default-unsafe-string, 4.06.0+beta1+flambda, 4.06.0+beta1+force-safe-string, 4.06.0+beta1+fp, 4.06.0+beta1+fp+flambda, 4.06.0+beta2, 4.06.0+beta2+afl, 4.06.0+beta2+default-unsafe-string, 4.06.0+beta2+flambda, 4.06.0+beta2+force-safe-string, 4.06.0+beta2+fp, 4.06.0+beta2+fp+flambda, 4.06.0+trunk, 4.06.0+trunk+afl, 4.06.0+trunk+flambda, 4.06.0+trunk+fp, 4.06.0+trunk+fp+flambda, 4.06.0+trunk+safe-string, 4.07.0+trunk, 4.07.0+trunk+afl, 4.07.0+trunk+flambda, 4.07.0+trunk+fp, 4.07.0+trunk+fp+flambda, 4.07.0+trunk+unsafe-string, system }
00:00.243  STATE                           REPOS     : { default }
00:00.243  STATE                           PACKAGES  : 7657 packages
00:00.243  STATE                           INSTALLED : { alcotest.0.8.1, astring.0.8.3, base.v0.9.3, base-bigarray.base, base-bytes.base, base-num.base, base-threads.base, base-unix.base, base64.2.2.0, biniou.1.2.0, camlp4.4.05+1, camomile.0.8.6, cmdliner.1.0.2, cohttp.0.99.0, cohttp-lwt.0.99.0, conduit.1.0.0, conf-gmp.1, conf-gmp-powm-sec.1, conf-libpcre.1, conf-m4.1, conf-openssl.1, conf-perl.1, conf-pkg-config.1.0, conf-which.1, conf-zlib.1, configurator.v0.9.1, cppo.1.6.0, cppo_ocamlbuild.1.6.0, cryptokit.1.12, dbm.1.0, depext.1.0.5, easy-format.1.3.0, fieldslib.v0.9.0, fmt.0.8.4, ipaddr.2.8.0, jbuilder.1.0+beta14, jsonm.1.0.1, lambda-term.1.11, lambdasoup.0.6.1, logs.0.6.2, lwt.2.7.1, lwt_react.1.0.0, lwt_ssl.1.0.0, magic-mime.1.1.0, markup.0.7.5, merlin.3.0.3, num.0, oasis.0.4.10, ocaml-compiler-libs.v0.9.0, ocaml-migrate-parsetree.1.0.6, ocamlbuild.0.11.0, ocamlfind.1.7.3, ocamlgraph.1.8.8, ocamlify.0.0.1, ocamlmod.0.0.9, ocamlnet.4.1.4, ocsigenserver.2.8, octavius.1.1.0, pcre.7.3.3, ppx_ast.v0.9.1, ppx_base.v0.9.0, ppx_compare.v0.9.0, ppx_core.v0.9.0, ppx_driver.v0.9.1, ppx_enumerate.v0.9.0, ppx_fields_conv.v0.9.0, ppx_hash.v0.9.0, ppx_js_style.v0.9.0, ppx_metaquot.v0.9.0, ppx_optcomp.v0.9.0, ppx_sexp_conv.v0.9.0, ppx_tools.5.0+4.05.0, ppx_tools_versioned.5.0.1, ppx_traverse_builtins.v0.9.0, ppx_type_conv.v0.9.0, re.1.7.1, react.1.2.1, result.1.2, sexplib.v0.9.2, ssl.0.5.5, stdio.v0.9.0, stringext.1.5.0, topkg.0.9.1, tyxml.4.1.0, uchar.0.0.2, uri.1.9.4, utop.2.0.1, uutf.1.0.1, yojson.1.4.0, zarith.1.7, zed.1.5 }
00:00.243  STATE                           ROOTS     : { alcotest.0.8.1, base-bigarray.base, base-threads.base, base-unix.base, cohttp.0.99.0, cohttp-lwt.0.99.0, depext.1.0.5, lambdasoup.0.6.1, lwt.2.7.1, lwt_ssl.1.0.0, merlin.3.0.3, oasis.0.4.10, ocamlgraph.1.8.8, ocsigenserver.2.8, re.1.7.1, ssl.0.5.5, uri.1.9.4, utop.2.0.1 }
00:00.243  STATE                           REINSTALL : {}
00:00.243  STATE                           State install loaded in 0.107s
00:00.244  FILE(export)                    Wrote ~/.opam/4.05.0/backup/state-20170927152010.export in 0.000s
00:00.300  CLIENT                          INSTALL eliom
00:00.767  CLIENT                          Orphans: full {}, versions {}
00:00.852  SOLVER                          resolve request=install:(eliom) remove:() upgrade:()
00:00.852  SOLVER                          cudf_versions_map
00:00.980  SOLVER                          Load cudf universe (depopts:false, build:true)
00:01.832  CUDF                            resolve request=install:(eliom) remove:() upgrade:() criteria:"-count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)"
00:03.626  SYSTEM                          [log-26815-ccabea] (in 0.001s) aspcud /home/yago/.opam/log/solver-in-26815-4bcc67 /home/yago/.opam/log/solver-out-26815-dd682e -count(removed),-notuptodate(request),-sum(request,version-lag),-count(down),-notuptodate(changed),-count(changed),-notuptodate(solution),-sum(solution,version-lag)
00:03.626  SYSTEM                          rm /home/yago/.opam/log/solver-in-26815-4bcc67
00:03.627  SYSTEM                          rm /home/yago/.opam/log/solver-out-26815-dd682e
00:03.928  CLIENT                          conflict!
Sorry, no solution found: there seems to be a problem with your request.

No solution found, exiting
00:03.928  STATE                           LOAD-STATE(switch-backup-err)
00:03.956  STATE                           Loaded /home/yago/.opam/state.cache in 0.027s
00:04.096  STATE                           ROOT      : /home/yago/.opam
00:04.096  STATE                           SWITCH    : 4.05.0
00:04.097  STATE                           COMPILER  : 4.05.0
00:04.097  STATE                           COMPILERS : { 3.07, 3.07+1, 3.07+2, 3.08.0, 3.08.1, 3.08.2, 3.08.3, 3.08.4, 3.09.0, 3.09.1, 3.09.1+metaocaml, 3.09.2, 3.09.3, 3.10.0, 3.10.1, 3.10.2, 3.11.0, 3.11.1, 3.11.2, 3.12.0, 3.12.1, 4.00.0, 4.00.0+debug-runtime, 4.00.0+fp, 4.00.1, 4.00.1+BER, 4.00.1+PIC, 4.00.1+annot, 4.00.1+debug-runtime, 4.00.1+french, 4.00.1+mirage-unix, 4.00.1+mirage-xen, 4.00.1+open-types, 4.00.1+raspberrypi, 4.00.1+short-types, 4.01.0, 4.01.0+32bit, 4.01.0+BER, 4.01.0+PIC, 4.01.0+armv6-freebsd, 4.01.0+fp, 4.01.0+lsb, 4.01.0+musl, 4.01.0+musl+static, 4.01.0+open-types, 4.01.0+profile, 4.02.0, 4.02.0+PIC, 4.02.0+improved-errors, 4.02.0+modular-implicits, 4.02.0+rc1, 4.02.0+trunk, 4.02.1, 4.02.1+32bit, 4.02.1+BER, 4.02.1+PIC, 4.02.1+fp, 4.02.1+modular-implicits-ber, 4.02.1+musl, 4.02.1+musl+static, 4.02.2, 4.02.2+improved-errors, 4.02.2+rc1, 4.02.3, 4.02.3+32bit, 4.02.3+PIC, 4.02.3+buckle-1, 4.02.3+buckle-master, 4.02.3+bytecode-only, 4.02.3+curried-constr, 4.02.3+fp, 4.02.3+musl, 4.02.3+musl+static, 4.02.3+termux, 4.03.0, 4.03.0+32bit, 4.03.0+beta1, 4.03.0+beta1+flambda, 4.03.0+beta1-no-debug, 4.03.0+beta2, 4.03.0+beta2+flambda, 4.03.0+beta2-no-debug, 4.03.0+fPIC, 4.03.0+flambda, 4.03.0+fp, 4.03.0+fp+flambda, 4.03.0+statistical-memprof, 4.03.0+termux, 4.03.0+trunk, 4.03.0+trunk+flambda, 4.03.0+trunk+fp, 4.03.0+trunk+fp+flambda, 4.04.0, 4.04.0+32bit, 4.04.0+BER, 4.04.0+afl, 4.04.0+beta1, 4.04.0+beta1+flambda, 4.04.0+beta2, 4.04.0+beta2+flambda, 4.04.0+bytecode-only, 4.04.0+copatterns, 4.04.0+fPIC, 4.04.0+flambda, 4.04.0+fp, 4.04.0+fp+flambda, 4.04.0+safe-string, 4.04.0+spacetime, 4.04.0+termux, 4.04.0+trunk+forced_lto, 4.04.1, 4.04.1+32bit, 4.04.1+bytecode-only, 4.04.1+fPIC, 4.04.1+flambda, 4.04.1+fp, 4.04.1+fp+flambda, 4.04.1+safe-string, 4.04.1+spacetime, 4.04.2, 4.04.2+32bit, 4.04.2+bytecode-only, 4.04.2+fPIC, 4.04.2+flambda, 4.04.2+fp, 4.04.2+fp+flambda, 4.04.2+safe-string, 4.04.2+spacetime, 4.05.0, 4.05.0+afl, 4.05.0+beta1, 4.05.0+beta1+flambda, 4.05.0+beta2, 4.05.0+beta2+flambda, 4.05.0+beta3, 4.05.0+flambda, 4.05.0+lto, 4.05.0+musl+static+flambda, 4.05.0+rc1, 4.05.0+rc1+flambda, 4.05.0+safe-string, 4.05.0+spacetime, 4.05.0+trunk, 4.05.0+trunk+afl, 4.05.0+trunk+flambda, 4.05.0+trunk+fp, 4.05.0+trunk+fp+flambda, 4.05.0+trunk+safe-string, 4.06.0+beta1, 4.06.0+beta1+afl, 4.06.0+beta1+default-unsafe-string, 4.06.0+beta1+flambda, 4.06.0+beta1+force-safe-string, 4.06.0+beta1+fp, 4.06.0+beta1+fp+flambda, 4.06.0+beta2, 4.06.0+beta2+afl, 4.06.0+beta2+default-unsafe-string, 4.06.0+beta2+flambda, 4.06.0+beta2+force-safe-string, 4.06.0+beta2+fp, 4.06.0+beta2+fp+flambda, 4.06.0+trunk, 4.06.0+trunk+afl, 4.06.0+trunk+flambda, 4.06.0+trunk+fp, 4.06.0+trunk+fp+flambda, 4.06.0+trunk+safe-string, 4.07.0+trunk, 4.07.0+trunk+afl, 4.07.0+trunk+flambda, 4.07.0+trunk+fp, 4.07.0+trunk+fp+flambda, 4.07.0+trunk+unsafe-string, system }
00:04.097  STATE                           REPOS     : { default }
00:04.097  STATE                           PACKAGES  : 7657 packages
00:04.097  STATE                           INSTALLED : { alcotest.0.8.1, astring.0.8.3, base.v0.9.3, base-bigarray.base, base-bytes.base, base-num.base, base-threads.base, base-unix.base, base64.2.2.0, biniou.1.2.0, camlp4.4.05+1, camomile.0.8.6, cmdliner.1.0.2, cohttp.0.99.0, cohttp-lwt.0.99.0, conduit.1.0.0, conf-gmp.1, conf-gmp-powm-sec.1, conf-libpcre.1, conf-m4.1, conf-openssl.1, conf-perl.1, conf-pkg-config.1.0, conf-which.1, conf-zlib.1, configurator.v0.9.1, cppo.1.6.0, cppo_ocamlbuild.1.6.0, cryptokit.1.12, dbm.1.0, depext.1.0.5, easy-format.1.3.0, fieldslib.v0.9.0, fmt.0.8.4, ipaddr.2.8.0, jbuilder.1.0+beta14, jsonm.1.0.1, lambda-term.1.11, lambdasoup.0.6.1, logs.0.6.2, lwt.2.7.1, lwt_react.1.0.0, lwt_ssl.1.0.0, magic-mime.1.1.0, markup.0.7.5, merlin.3.0.3, num.0, oasis.0.4.10, ocaml-compiler-libs.v0.9.0, ocaml-migrate-parsetree.1.0.6, ocamlbuild.0.11.0, ocamlfind.1.7.3, ocamlgraph.1.8.8, ocamlify.0.0.1, ocamlmod.0.0.9, ocamlnet.4.1.4, ocsigenserver.2.8, octavius.1.1.0, pcre.7.3.3, ppx_ast.v0.9.1, ppx_base.v0.9.0, ppx_compare.v0.9.0, ppx_core.v0.9.0, ppx_driver.v0.9.1, ppx_enumerate.v0.9.0, ppx_fields_conv.v0.9.0, ppx_hash.v0.9.0, ppx_js_style.v0.9.0, ppx_metaquot.v0.9.0, ppx_optcomp.v0.9.0, ppx_sexp_conv.v0.9.0, ppx_tools.5.0+4.05.0, ppx_tools_versioned.5.0.1, ppx_traverse_builtins.v0.9.0, ppx_type_conv.v0.9.0, re.1.7.1, react.1.2.1, result.1.2, sexplib.v0.9.2, ssl.0.5.5, stdio.v0.9.0, stringext.1.5.0, topkg.0.9.1, tyxml.4.1.0, uchar.0.0.2, uri.1.9.4, utop.2.0.1, uutf.1.0.1, yojson.1.4.0, zarith.1.7, zed.1.5 }
00:04.097  STATE                           ROOTS     : { alcotest.0.8.1, base-bigarray.base, base-threads.base, base-unix.base, cohttp.0.99.0, cohttp-lwt.0.99.0, depext.1.0.5, lambdasoup.0.6.1, lwt.2.7.1, lwt_ssl.1.0.0, merlin.3.0.3, oasis.0.4.10, ocamlgraph.1.8.8, ocsigenserver.2.8, re.1.7.1, ssl.0.5.5, uri.1.9.4, utop.2.0.1 }
00:04.097  STATE                           REINSTALL : {}
00:04.097  STATE                           State switch-backup-err loaded in 0.161s
00:04.097  SYSTEM                          rm /home/yago/.opam/4.05.0/backup/state-20170927152010.export
00:04.098  SYSTEM                          Lock released on /home/yago/.opam/4.05.0/lock
00:04.098  SYSTEM                          Lock released on /home/yago/.opam/lock
```

**Comment by dbuenzli** [comment]
I'm sorry I can't help further it seems a problem the request to `aspcud`, please run the failing command with the `--cudf` option and post the resulting file somewhere so that solver experts (i.e. @AltGr...) can have a look.

**Comment by dbuenzli** [comment]
Btw. do you have additional `opam repository`  or just the default one ?

**Comment by yannham** [comment]
Thanks for your help. I only have the default repository. When I use `opam install eliom --cudf opam.log`, the log file is totally empty, even if I use `--debug`.

**Comment by dbuenzli** [comment]
Can you run `apscud --version` from your shell at all ?

**Comment by yannham** [comment]
It outputs

```
aspcud version 1.9.4

License: The MIT License <https://opensource.org/licenses/MIT>
```

**Comment by AltGr** [comment]
The error message basically means "the solver failed to return a solution, and Dose [the library interacting with the solver] failed to return the explanation why". So it's basically a bug in one of the layers.
If you run with `--cudf dump-file` and provide me with the generated `dump-file*.cudf` I may try and see what happens when running the solver directly on the same input. It's likely this is fixed in 2.0.0~beta4, though.

**Comment by dbuenzli** [comment]
@yannham mentioned the cudf file is empty.

**Comment by AltGr** [comment]
Ah, sorry, missed that part... in any case, this is surely a bug, but most likely fixed in 2.0.0 already.

**Comment by AltGr** [comment]
Thanks for reporting. Please reopen if there is further info for opam 2.0.0

**Comment by NightBlues** [comment]
@AltGr the problem is still reproducable: for 4.08 ocaml I do:
```
$ opam install -vvv ppx_deriving
+ /home/nightblues/.opam/4.08.0+flambda/bin/ocamlc "-vnum"
- 4.08.0
Sorry, no solution found: there seems to be a problem with your request.

No solution found, exiting
'opam install -vvv ppx_deriving' failed.
```
The reason for this case is that ppx_deriving depends on ppx_tools, that has ocaml < 4.08 dependency, but I've found it manually.
```
$ opam config report
# opam config report
# opam-version      2.0.3 
# self-upgrade      no
# system            arch=x86_64 os=linux os-distribution=debian os-version=10
# solver            aspcud
# install-criteria  -count(removed),-sum(request,version-lag),-count(down),-sum(solution,version-lag),-count(changed)
# upgrade-criteria  -count(down),-count(removed),-sum(solution,version-lag),-count(new)
# jobs              7
# repositories      1 (http) (default repo at 15d59d7e)
# pinned            0
# current-switch    4.08.0+flambda
$ aspcud --version
aspcud version 1.9.4

License: The MIT License <https://opensource.org/licenses/MIT>
```
